# Generated by Django 3.1.3 on 2022-03-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201118_1003'),
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='results',
            field=models.ManyToManyField(related_name='results', to='users.Profile'),
        ),
    ]
