# Generated by Django 3.1.3 on 2022-03-28 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_auto_20201118_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='time_slot',
            field=models.TextField(default='', max_length=100),
        ),
    ]
