# Generated by Django 3.1.3 on 2022-03-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20220328_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='time_slot',
            field=models.TextField(default='--------', max_length=100),
        ),
    ]
